In [4]:
# Load libraries
import numpy as np
import pandas as pd
from sklearn import metrics  # Import scikit-learn metrics module for accuracy calculation
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier  # import the classifier

In [24]:
df = pd.read_csv("Book_Restaurant_Dataset.csv", header=None)
df

,0,1,2,3,4,5,6,7,8,9,10
0,Yes,No,No,Yes,Some,$$$,No,Yes,French,0-10,Yes
1,Yes,No,No,Yes,Full,$,No,No,Thai,30-60,No
2,No,Yes,No,No,Some,$,No,No,Burger,0-10,Yes
3,Yes,No,Yes,Yes,Full,$,No,No,Thai,10-30,Yes
4,Yes,No,Yes,No,Full,$$$,No,Yes,French,>60,No
5,No,Yes,No,Yes,Some,$$,Yes,Yes,Italian,0-10,Yes
6,No,Yes,No,No,None,$,Yes,No,Burger,0-10,No
7,No,No,No,Yes,Some,$$,Yes,Yes,Thai,0-10,Yes
8,No,Yes,Yes,No,Full,$,Yes,No,Burger,>60,No
9,Yes,Yes,Yes,Yes,Full,$$$,No,Yes,Italian,10-30,No
10,No,No,No,No,None,$,No,No,Thai,0-10,No
11,Yes,Yes,Yes,Yes,Full,$,No,No,Burger,30-60,Yes

In [25]:

string_to_int = preprocessing.LabelEncoder()  # encode your data
df = df.apply(string_to_int.fit_transform)  # fit and transform it

In [28]:
# To divide our data into attribute set and Label:
X = df.iloc[:, 0:10]  # contains the attribute
y = df.iloc[:, 10]  # contains the label

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train, y_train, sep='\n')

    0  1  2  3  4  5  6  7  8  9
9   1  3  3  3  3  2  3  1  3  7
0   1  2  0  1  4  2  3  1  2  3
4   1  2  1  2  0  2  3  1  2  5
1   1  2  0  1  3  0  0  0  1  2
7   0  0  0  1  4  1  2  3  4  0
8   0  1  3  2  0  0  1  2  0  5
5   0  1  2  1  4  1  2  3  3  6
2   0  1  2  0  2  0  0  0  0  3
10  0  0  0  0  1  0  0  0  1  0
9     3
0     2
4     0
1     3
7     2
8     0
5     2
2     2
10    1
Name: 10, dtype: int64

In [31]:
# To divide our data into training and test sets:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# perform training

classifier = DecisionTreeClassifier(criterion="entropy")  # create a classifier object
classifier.fit(X_train, y_train)  # fit the classifier with X and Y data

DecisionTreeClassifier(criterion='entropy')

In [34]:
# Predict the response for test dataset
y_pred = classifier.predict(X_test)
print(y_pred)
pred = classifier.predict([[1, 2, 1, 2, 0, 2, 3, 1, 2, 5]])
print(pred)

# Model Accuracy, how often is the classifier correct?


print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

[2 1 4]
[0]
Accuracy: 1.0